swagger: "2.0"
info:
  title: "API - Banco Digital"
  version: "2.0"
  description: "Modelagem de API de um banco digital"
  contact:
    name: "Support"
    email: "kariinagomes_@hotmail.com"
host: "bancodigital"
basePath: "/v1"
schemes: 
  - "http"
  - "https"
tags:
  - name: "Conta"
    description: "Criação de conta e consultas relacionadas a mesma"
  - name: "Favorecido"
    description: "Inclusão, edição e exclusão de favorecidos"
  - name: "Transferência"
    description: "Realizar e visualizar as transferências"

paths:
  /conta:
    post:
      tags:
        - "Conta"
      summary: "Cria uma nova conta bancária"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "conta"
          schema:
            $ref: "#/definitions/Conta"
      responses:
        201:
          description: "Conta cadastrada com sucesso"
          schema:
            $ref: "#/definitions/Conta"
        400:
          description: "Entrada inválida"
  /conta/{numeroAgencia}/{numeroConta}/saldo:
    get:
      tags: 
        - "Conta"
      summary: "Consulta o saldo da conta bancária"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "numeroAgencia"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "numeroConta"
          type: "integer"
          format: "int32"
          required: true
      responses:
        200:
          description: "Consulta do saldo realizada com sucesso"
          schema: 
            $ref: "#/definitions/Conta"
        401:
          description: "Sem permissão de acesso"
        403:
          description: "Sem permissão de acesso"
  /conta/{numeroAgencia}/{numeroConta}/extrato:
    get:
      tags:
        - "Conta"
      summary: "Consulta o extrato da conta bancária"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "numeroAgencia"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "numeroConta"
          type: "integer"
          format: "int32"
          required: true
      responses:
        200: 
          description: "Consulta do extrato realizada com sucesso"
          schema:
            $ref: "#/definitions/Transacao"
        401:
          description: "Sem permissão de acesso"
        403:
          description: "Sem permissão de acesso"
  /conta/{numeroAgencia}/{numeroConta}/favorecido:
    post:
      tags:
        - "Favorecido"
      summary: "Cadastra um novo favorecido"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "numeroAgencia"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "numeroConta"
          type: "integer"
          format: "int32"
          required: true
        - in: "body"
          name: "favorecido"
          schema:
            $ref: "#/definitions/Favorecido"
      responses:
        201:
          description: "Favorecido cadastrado com sucesso"
          schema: 
            $ref: "#/definitions/Favorecido"
        400:
          description: "Entrada inválida"
  /conta{numeroAgencia}/{numeroConta}/favorecido/{favorecidoId}:
    put:
      tags:
        - "Favorecido"
      summary: "Edita um favorecido"
      consumes: 
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "numeroAgencia"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "numeroConta"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "favorecidoId"
          type: "integer"
          format: "int64"
          required: true
        - in: "body"
          name: "favorecido"
          required: true
          schema:
            $ref: "#/definitions/Favorecido"
      responses:
        200: 
          description: "Favorecido atualizado"
          schema:
            $ref: "#/definitions/Favorecido"
        401: 
          description: "Sem permissão de acesso"
        403: 
          description: "Sem permissão de acesso"
    delete:
      tags: 
        - "Favorecido"
      summary: "Remove um favorecido"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "numeroAgencia"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "numeroConta"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "favorecidoId"
          type: "integer"
          format: "int64"
          required: true
      responses:
        204:
          description: "Favorecido removido com sucesso"
        400:
          description: "Requisição inválida"
        401:
          description: "Sem permissão de acesso"
        403:
          description: "Sem permissão de acesso"
  /conta/{numeroAgencia}/{numeroConta}/transacao:
    post: 
      tags: 
        - "Transferência"
      summary: "Realiza uma nova transferência bancária"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "numeroAgencia"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "numeroConta"
          type: "integer"
          format: "int32"
          required: true
        - in: "body"
          name: "transacao"
          required: true
          schema: 
            $ref: "#/definitions/Transacao"
      responses:
        201:
          description: "Transferência realizada"
          schema:
            $ref: "#/definitions/Transacao"
        400: 
          description: "Entrada inválida"
        401:
          description: "Sem permissão de acesso"
        403:
          description: "Sem permissão de acesso"
    get:
      tags:
        - "Transferência"
      summary: "Consulta as transferências bancárias"
      produces:
        - "application/json"
      parameters: 
        - in: "path"
          name: "numeroAgencia"
          type: "integer"
          format: "int32"
          required: true
        - in: "path"
          name: "numeroConta"
          type: "integer"
          format: "int32"
          required: true
      responses:
        200:
          description: "Consulta realizada"
          schema:
            $ref: "#/definitions/Transacao"
        401:
          description: "Sem permissão de acesso"
        403:
          description: "Sem permissão de acesso"
        
definitions:
  Conta:
    type: "object"
    properties:
      id: 
        type: "integer"
        format: "int64"
      saldo:
        type: "number"
        format: "double"
      pessoa:
        $ref: "#/definitions/Pessoa"
  Favorecido:
    type: "object"
    properties:
      id: 
        type: "integer"
        format: "int64"
      nomeBanco: 
        type: "string"
      pessoa: 
        $ref: "#/definitions/Pessoa"
  Pessoa:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      cpf:
        type: "integer"
        format: "int64"
      numeroAgencia:
        type: "integer"
        format: "int32"
      numeroConta: 
        type: "integer"
        format: "int32"
  Transacao:
    type: "object"
    properties:
      id: 
        type: "integer"
        format: "int64"
      dataTransacao: 
        type: "string"
        format: "date"
      valor:
        type: "number"
        format: "float"
